class AdventureError(Exception):
    pass

class ExitNotFoundError(AdventureError):
    pass